# -*- coding: utf-8 -*-
"""convert_to_jsonl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fmxbE5DSLjQStC3CKIueHJ-WTQ3rG6cN

#Preprocessing and Checking Dataset
"""

import pandas as pd

# Baca file CSV yang sudah diupload
df2 = pd.read_csv("kue_tradisional_kedua.csv", delimiter=';', encoding='latin1')

# Lihat 5 baris pertama
display(df2.head(10))

df2['cara_pembuatan'].isna().sum()

df2['sejarah_kue'].isna().sum()

df2.loc[df2['nama_kue'] == 'Apem gula merah', 'sejarah_kue'] = "Apem gula merah adalah kue tradisional khas Jawa yang sudah dikenal sejak zaman dahulu. Kata apem diyakini berasal dari bahasa India Selatan, “appam”, sejenis kue kukus dari tepung beras yang dibawa oleh pedagang India ke Nusantara. Setelah diadaptasi dengan bahan lokal seperti gula kelapa dan santan, muncullah variasi rasa yang khas: apem gula merah."

df2['sejarah_kue'].isna().sum()

# Tampilkan baris yang masih kosong atau belum terisi di kolom sejarah_kue, daerah_kue, atau cara_pembuatan
df_kosong = df2[
    (df2['sejarah_kue'].isna()) |
    (df2['daerah_kue'].isna()) |
    (df2['cara_pembuatan'].isna()) |
    (df2['sejarah_kue'] == "Belum tersedia di Wikipedia") |
    (df2['daerah_kue'] == "Belum tersedia di Wikipedia") |
    (df2['cara_pembuatan'] == "Belum tersedia di Wikipedia") |
    (df2['sejarah_kue'].astype(str).str.strip() == "") |
    (df2['daerah_kue'].astype(str).str.strip() == "") |
    (df2['cara_pembuatan'].astype(str).str.strip() == "")
]

# Lihat daftar kue yang masih belum lengkap
df_kosong[['nama_kue', 'sejarah_kue', 'daerah_kue', 'cara_pembuatan']]

# Hapus baris dengan nama_kue = "Kue"
df2 = df2[df2['nama_kue'] != 'Kue']

# Cek hasilnya
print("Jumlah data setelah dihapus:", len(df2))
df2[df2['nama_kue'] == 'Kue']

df2['sejarah_kue'].isna().sum()

df2['cara_pembuatan'].isna().sum()

df2['gambar'].isna().sum()

df2['link_sumber'].isna().sum()

# Tampilkan baris yang link_sumber-nya masih NaN
df2[df2['link_sumber'].isna()][['nama_kue', 'link_sumber']]

df2.loc[df2['nama_kue'] == 'Bay tat', 'link_sumber'] = "https://id.wikipedia.org/wiki/Bay_tat"

df2.loc[df2['nama_kue'] == 'Bika Ambon', 'link_sumber'] = "https://id.wikipedia.org/wiki/Bika_Ambon"

df2.loc[df2['nama_kue'] == 'Cu-chong-kao', 'link_sumber'] = "https://id.wikipedia.org/wiki/Cu-chong-kao"

df2.loc[df2['nama_kue'] == 'Kaasstengels', 'link_sumber'] = "https://id.wikipedia.org/wiki/Kaasstengels"

display(df2.head(10))

import requests
import pandas as pd
import time
import json

# Pastikan df2 sudah ada
kue_list = df2[['nama_kue']].dropna().reset_index(drop=True)

gambar_list = []

for i, row in kue_list.iterrows():
    nama = row['nama_kue']

    params = {
        "action": "query",
        "titles": nama,
        "prop": "pageimages",
        "pithumbsize": 500,
        "format": "json"
    }

    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                      "(KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
    }

    try:
        r = requests.get("https://id.wikipedia.org/w/api.php", params=params, headers=headers, timeout=10)
        r.raise_for_status()  # biar error 403/404 langsung ketangkap

        data = r.json()
        page = next(iter(data["query"]["pages"].values()))
        img_url = page.get("thumbnail", {}).get("source", None)

        gambar_list.append({
            "nama_kue": nama,
            "gambar": img_url if img_url else None
        })

        print(f"{i+1}/{len(kue_list)} - {nama}: {'Ada gambar' if img_url else 'Tidak ada gambar'}")

    except requests.exceptions.HTTPError as e:
        print(f"{i+1}/{len(kue_list)} - {nama}: Gagal ({e})")
        gambar_list.append({"nama_kue": nama, "gambar": None})
    except Exception as e:
        print(f"{i+1}/{len(kue_list)} - {nama}: Error ({e})")
        gambar_list.append({"nama_kue": nama, "gambar": None})

    time.sleep(0.5)  # delay biar gak dianggap spam

df_gambar = pd.DataFrame(gambar_list)
ada_gambar = df_gambar[df_gambar['gambar'].notna()]
tidak_ada_gambar = df_gambar[df_gambar['gambar'].isna()]

print("\n===== HASIL CEK GAMBAR =====")
print(f"Kue dengan gambar  : {len(ada_gambar)}")
print(f"Kue tanpa gambar   : {len(tidak_ada_gambar)}")

display(ada_gambar.head(10))
display(tidak_ada_gambar.head(10))

# Pastikan nama kolom di df_gambar sama: 'nama_kue' dan 'gambar'
df2.set_index('nama_kue', inplace=True)
df_gambar.set_index('nama_kue', inplace=True)

# Isi kolom 'gambar' yang masih kosong dengan URL dari df_gambar
df2['gambar'].update(df_gambar['gambar'])

# Kembalikan index ke default (biar rapi lagi)
df2.reset_index(inplace=True)

df2[['nama_kue', 'gambar']].head(10)

df2.loc[df2['nama_kue'] == 'Apam barenda', 'gambar'].values[0]

display(tidak_ada_gambar.head(45))

update_gambar = {
    "Adee": "https://drive.google.com/file/d/1UeiuO6gmvqUkURsqCiN-czgKn_TIsIAz/view?usp=drive_link",
    "Baroncong": "https://drive.google.com/file/d/1yUvY2Z5mZ4-ecBbeLns-3sBe1b7u1iY9/view?usp=drive_link",
    "Binyolos": "https://drive.google.com/file/d/1ha8zj3MMLjpFAP25hKJRVz9ij1DQgpTH/view?usp=drive_link",
    "Bobengka": "https://drive.google.com/file/d/1P_WjcvV7w9Ix3oFv-n49MnKqYly3p4Uz/view?usp=drive_link",
    "Boh Rom-Rom": "https://drive.google.com/file/d/1xGvS37yqBMyLcRlkp3ywNapqgiJ7Tm8Q/view?usp=drive_link",
    "Boh usen": "https://drive.google.com/file/d/1MUqtxvGz2BWbqH_6AAEBZGcY_Gnx1-62/view?usp=drive_link",
    "Bolu suri": "https://drive.google.com/file/d/1_KP4m6ti0LJMRbkkRSrbRNzq2FRwiuut/view?usp=drive_link",
    "Candil": "https://drive.google.com/file/d/18Uu54zxnf1oNVbssGoMDb_jHYMQavDbI/view?usp=drive_link",
    "Deram-deram": "https://drive.google.com/file/d/1288KJTlpzisOfQgyWWkLpmLe3aNTujKr/view?usp=drive_link",
    "Dumbeg": "https://drive.google.com/file/d/112ZTB6Km1K5rU9M1UtzwbQUYKBewnb0Z/view?usp=drive_link",
    "Engkak Medok": "https://drive.google.com/file/d/1TV1lt1mTWVdu_3ZElSJ7tFvtNDR7yu8d/view?usp=drive_link",
    "Gandasturi": "https://drive.google.com/file/d/1FThhkQZCBs4V31wj2rAEfjrm7e4bIOYa/view?usp=drive_link",
    "Gomak ubi": "https://drive.google.com/file/d/16d0HUp9pcbS6PG5sYViJjapWdR6-7O3z/view?usp=drive_link",
    "Gulo puan": "https://drive.google.com/file/d/1c02FnFGbofBDTQsfFQZ63CkkX1Mq4oCi/view?usp=drive_link",
    "Jalabria": "https://drive.google.com/file/d/18bjeYshLN6HsqMJATAw9nvh18Jva-s-J/view?usp=drive_link",
    "Kaoya dudul": "https://drive.google.com/file/d/1Q8Yv-ibwho8_kFKQGgQgws7e2NwlPCCx/view?usp=drive_link",
    "Kue karas": "https://drive.google.com/file/d/10G7A735jSa15fmbliNOms49XJykbfQj2/view?usp=drive_link",
    "Kolong Klitik": "https://drive.google.com/file/d/1J4UWhlMRHW9YK94j_I94EUQZcVuRhNqf/view?usp=drive_link",
    "Kue bongkol": "https://drive.google.com/file/d/1FE24uSHoTcYmBJRP5Pghx63t9uBjHyoI/view?usp=drive_link",
    "Kue buah Melaka": "https://drive.google.com/file/d/1N-s1Rzd_EhS0vQ6NR0jTnpnN1RBGHBdW/view?usp=drive_link",
    "Kue cepak kapung": "https://drive.google.com/file/d/13uXOI5fOGkuZELZLeheqK6sLCQx4UE9t/view?usp=drive_link",
    "Kue gelenak": "https://drive.google.com/file/d/11XOXWlQt-8jZrRxkX3ZLFnfxS7hVsLEv/view?usp=drive_link",
    "Kue Inti": "https://drive.google.com/file/d/16lA4VShaRu9PN8AvjuvUikQOx1mP7xtT/view?usp=drive_link",
    "Kue jongkong": "https://drive.google.com/file/d/1qThiZZV9hy9hjWlcPgBcljBFy6wv6t2K/view?usp=drive_link",
    "Kue lasidah": "https://drive.google.com/file/d/1zKr8ji-EBWx6vG-VYP7b2gMN1QchOY9Z/view?usp=drive_link",
    "Kue lontar": "https://drive.google.com/file/d/1UtPuR42EpmR-RPdBSNSKpm34AYNrV25Z/view?usp=drive_link",
    "Kue pepe’": "https://drive.google.com/file/d/1APFSO8nuO8ByegrMlq7aV81VPwkMAd3N/view?usp=drive_link",
    "Kue Sanole": "https://drive.google.com/file/d/13iYyjr_2paUl9TMuY5OZUNupZe5QbxvJ/view?usp=drive_link",
    "Lambang sari": "https://drive.google.com/file/d/1QMrRk9CBHy3yvaEXFLFSLgH3NE77X_C8/view?usp=drive_link",
    "Lampam": "https://drive.google.com/file/d/107UNyu2YmF5OZHbTRjZPsfmoculciooq/view?usp=drive_link",
    "Lampu lampu": "https://drive.google.com/file/d/1LZp7iPgF9o-o0Dxlgc3gCvfTNvjQ_Z59/view?usp=drive_link",
    "Lapis kojo": "https://drive.google.com/file/d/1cgMAW90L_JnUWTEw2LX8Wcq5FRW_l-4p/view?usp=drive_link",
    "Lapis nanas": "https://drive.google.com/file/d/1WfNHYVgPFx_YU861j7Y-sSYm3NYCTVKh/view?usp=drive_link",
    "Kue Lupis": "https://drive.google.com/file/d/1corPx2f08ruzAnhrRARbJyPx2SkP1cyc/view?usp=drive_link",
    "Meniran (makanan)": "https://drive.google.com/file/d/1S3hLIsawYzgsVa2vSZKTWTODt1U8jYFU/view?usp=drive_link",
    "Kue Mentu": "https://drive.google.com/file/d/1sHV98bgxz5JULhzz7S5Pb_4d7z2qvZc6/view?usp=drive_link",
    "Pohul pohul": "https://drive.google.com/file/d/1UAFY0goVGIyu7GXxSva4b7eCV6if5Kzg/view?usp=drive_link",
    "Perut Punai": "https://drive.google.com/file/d/19GnVEFvEtO2EGswHsmTXXYQjOtL_Z4Gw/view?usp=drive_link",
    "Peunajoh tho": "https://drive.google.com/file/d/1m9Qvs5payWW6665dmBM7hxZP1bCTWvaZ/view?usp=drive_link",
    "Pia": "https://drive.google.com/file/d/1vRShjf69t6G66S6M5305BDfSE9vs1zF4/view?usp=drive_link",
    "Rara gudig": "https://drive.google.com/file/d/1ubUQMQ6VihSiWCdD8JdVohfhsWj_TjhM/view?usp=drive_link",
    "Rintak": "https://drive.google.com/file/d/16KVABhnyLndEgXqB8kqeNR5aI6QiCc6J/view?usp=drive_link",
    "Sunduk lawang": "https://drive.google.com/file/d/1TUKIqL7oef54RkouGaBplcp7XKV_YRwd/view?usp=drive_link",
    "Tipa tipa": "https://drive.google.com/file/d/1K_CB9ycn5Q7Q0_2RGTCwr2UkEmfntiRq/view?usp=drive_link",
    "Ulen-ulen": "https://drive.google.com/file/d/1_ArHXrWzNyAR7iUhr_vTkmaCC43xaEve/view?usp=drive_link"
}

for kue, link in update_gambar.items():
    df2.loc[df2['nama_kue'] == kue, 'gambar'] = link

df2[['nama_kue', 'gambar']].head(10)

df2.head(76)

df2['gambar'].isna().sum()

# Tampilkan baris yang link_sumber-nya masih NaN
df2[df2['gambar'].isna()][['nama_kue', 'gambar']]

update_gambar = {
    "Kue pepe": "https://drive.google.com/file/d/1APFSO8nuO8ByegrMlq7aV81VPwkMAd3N/view?usp=drive_link",
}

for kue, link in update_gambar.items():
    df2.loc[df2['nama_kue'] == kue, 'gambar'] = link

df2.isna().sum()

df2.info()

df2['nama_kue'].nunique()

df2[df2.duplicated(subset='nama_kue', keep=False)].sort_values('nama_kue')

df2['deskripsi'] = df2['deskripsi'].str.replace(r'[^\x00-\x7F]+', '', regex=True)
df2['sejarah_kue'] = df2['sejarah_kue'].str.replace(r'[^\x00-\x7F]+', '', regex=True)
df2['cara_pembuatan'] = df2['cara_pembuatan'].str.replace(r'[^\x00-\x7F]+', '', regex=True)

print("Nama unik:", df2['nama_kue'].nunique() == len(df2))
print("URL valid:", df2['gambar'].str.startswith('http').sum(), "dari", len(df2))

print("Total data:", len(df2))
print(df2.info())

def convert_drive_link(link):
    if "drive.google.com/file/d/" in link:
        file_id = link.split("/d/")[1].split("/")[0]
        return f"https://drive.google.com/uc?export=view&id={file_id}"
    return link

df2["gambar"] = df2["gambar"].apply(convert_drive_link)

df.head(5)

df2[["nama_kue", "gambar"]].head(10)

df2.to_csv("kue_tradisional_final_kedua.csv", index=False, encoding="utf-8-sig")
print("Dataset final berhasil disimpan sebagai 'kue_tradisional_final_kedua.csv'")

"""#Convert to JSONL"""

import pandas as pd
import json
import yaml
import os

cfg = yaml.safe_load(open("config/settings.yaml"))
csv_path = "dataset/kue_tradisional.csv"
jsonl_path = cfg["dataset"]["jsonl"]
cols = cfg["dataset"]["columns"]

df = pd.read_csv(csv_path)

os.makedirs(os.path.dirname(jsonl_path), exist_ok=True)

records = []
for i, row in df.iterrows():
    record = {
        "id": str(row.get(cols["id"], str(i))),
        "title": str(row.get(cols["name"], "")),
        "description": str(row.get(cols["description"], "")),
        "history": str(row.get(cols["history"], "")),
        "making_process": str(row.get(cols["making_process"], "")),
        "region": str(row.get(cols["region"], "")),
        "image": str(row.get(cols["image"], "")),
        "source": str(row.get(cols["source"], ""))
    }
    records.append(record)

with open(jsonl_path, "w", encoding="utf-8") as f:
    for rec in records:
        json.dump(rec, f, ensure_ascii=False)
        f.write("\n")

print("✓ JSONL berhasil dibuat:", jsonl_path)